# Generated by Django 3.1 on 2020-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtext',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
